### ISSUE TITLE
TypeError: value.map is not a function in header.js

### ISSUE THREAD

**Issue by aymather** [serviejs/servie#28]
I'm getting this error when receiving a response from an API.

<img width="886" alt="Screen Shot 2019-09-26 at 12 55 16 PM" src="https://user-images.githubusercontent.com/41848756/65720494-e8459c80-e05c-11e9-8f68-ca9be338d468.png">

I console.log'ed the inputs to the `append` method inside `/dist/header.js` and found some more information.

<img width="180" alt="Screen Shot 2019-09-26 at 12 56 36 PM" src="https://user-images.githubusercontent.com/41848756/65720671-50947e00-e05d-11e9-9b50-d5178549d106.png">

It looks like the `value` input variable is a number which is causing an error at `value.map(String)`

I wrapped the method in a `try/catch` block and I was able to run the request without getting errors, but I'd prefer to understand better why I'm getting this error. Am I doing something wrong? Or should I pull request for the simple error catch?

**Comment by blakeembrey** [comment]
What version are you using? I'm 99% sure this was fixed a couple months back: https://github.com/serviejs/servie/releases/tag/v4.3.0.

**Comment by aymather** [comment]
Shoot, yeah looks like I'm running `servie@4.2.1`

That's so weird, I just used `npm install` to install `node_modules`, wonder why the default is outdated.. sorry about that!

**Comment by blakeembrey** [comment]
@aymather I wouldn't have bumped any of the parent dependencies, did you have an existing installation (e.g. `popsicle -> servie` in https://github.com/serviejs/popsicle/blob/72dd636dc30fea6f32e749d3836e481664406c0c/package.json#L107)? It should install the latest version within the major range by default if you do `npm install popsicle`. Did you have a `package-lock.json` that maybe was pinned to an older version? Another workaround is that I can release an update on `popsicle` 😄

**Comment by aymather** [comment]
Looks like you were right, this was in the `package-lock.json` of the parent directory, which was another dependency.

<img width="889" alt="Screen Shot 2019-09-26 at 1 24 34 PM" src="https://user-images.githubusercontent.com/41848756/65722430-188f3a00-e061-11e9-99f7-5448d1485d38.png">

So I should update this to be version `4.3.0` correct?

**Comment by blakeembrey** [comment]
@aymather If you do an `npm install <dependency>` it should be updating the `package-lock.json` for you.

**Comment by aymather** [comment]
Ok, I updated the dependency by running `npm install servie` which updated the `package-lock.json` to `v4.3.1` and everything works now. This is no longer an issue with servie. Thanks so much for the help <3
