### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [serviejs/servie#46]
Hey there!

I belong to an open source security research community, and a member (@sampaguitas) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by blakeembrey** [comment]
For now you can email hello@blakeembrey.com until I have set up a good channel for this.

**Comment by JamieSlome** [comment]
@blakeembrey - thanks for the collaboration here and on #47.

I have sent you an e-mail with further details 👍 Just for reference, you can view the contents of the report here too:

https://huntr.dev/bounties/571d66f2-60c7-49bd-a533-d753154fc91a

It is private and only accessible to maintainers with repository write permissions.

**Comment by blakeembrey** [comment]
Closing as resolved with https://github.com/serviejs/popsicle-redirects/releases/tag/v1.1.1

**Comment by JamieSlome** [comment]
Thanks for the response and follow up @blakeembrey!

I will adjust the repository that the report is pointing to so that we can confirm a fix, and make the report public too 👍
